[package]
name = "protocol_mitm"
version = "0.1.0"
authors = ["CodeTiger"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/codetiger/VacuumTiger"

[dependencies]
chrono = "0.4"
libc = "0.2"
